Repository ardatan/graphql-tools, pull requests merged in 2018-09, with the labels that each got.

#946 Correct description on mocking
  docs/source/mocking.md
Labels: docs

#934 missing comma in doc
  docs/source/schema-directives.md
Labels: docs

#933 Adjust Fetcher interface in docs
  CHANGELOG.md
  docs/source/remote-schemas.md
Labels: docs

#948 Extract input extensions in extractExtensionDefinitions
  CHANGELOG.md
  src/generate/extractExtensionDefinitions.ts
  src/test/testExtensionExtraction.ts
  src/test/tests.ts
Labels: feature, to do

#928 Remove Object Spreading for Transformed Subscription Results
  CHANGELOG.md
  src/stitching/delegateToSchema.ts
Labels: bug

#925 Pass and Check for Error Extensions
  CHANGELOG.md
  src/stitching/errors.ts
  src/test/testErrors.ts
Labels: bug

#953 Update to `graphql-js` 14.x
  .travis.yml
  .vscode/settings.json
  CHANGELOG.md
  package.json
  src/generate/addResolveFunctionsToSchema.ts
  src/makeExecutableSchema.ts
  src/mock.ts
  src/schemaVisitor.ts
  src/stitching/delegateToSchema.ts
  src/stitching/errors.ts
  src/stitching/mergeSchemas.ts
  src/stitching/schemaRecreation.ts
  src/stitching/typeFromAST.ts
  src/test/testDirectives.ts
  src/test/testErrors.ts
  src/test/testMergeSchemas.ts
  src/test/testSchemaGenerator.ts
  src/test/testTransforms.ts
  src/test/testingSchemas.ts
  src/transforms/ConvertEnumValues.ts
  src/transforms/transformSchema.ts
  tsconfig.json
Labels: in progress
