Repository ardatan/graphql-tools, pull requests merged in 2018-05, with the labels that each got.

#763 Fix fragments bug in ReplaceFieldWithFragment
  docs/source/schema-transforms.md
  src/transforms/ReplaceFieldWithFragment.ts
Labels: bug

#772 Fix right schema reference in onTypeConflict info
  src/stitching/mergeSchemas.ts
Labels: bug

#779 Update remote schema docs with async/await
  docs/source/remote-schemas.md
Labels: docs

#803 Add option to skip validation in delegateToSchema
  src/Interfaces.ts
  src/stitching/delegateToSchema.ts
Labels: feature
