Repository ardatan/graphql-tools, pull requests merged in 2020-09, with the labels that each got.

#1971 enable batch execution
  packages/batch-delegate/tests/typeMerging.example.test.ts
  packages/delegate/package.json
  packages/delegate/src/delegateToSchema.ts
  packages/delegate/src/getBatchingExecutor.ts
  packages/delegate/src/memoize.ts
  packages/delegate/src/mergeExecutionParams.ts
  packages/delegate/src/prefix.ts
  packages/delegate/src/splitResult.ts
  packages/delegate/src/types.ts
  packages/delegate/tests/batchExecution.test.ts
  packages/stitch/tests/alternateStitchSchemas.test.ts
  packages/stitch/tests/fixtures/schemas.ts
  packages/stitch/tests/stitchSchemas.test.ts
  packages/stitch/tests/typeMerging.test.ts
Labels: feature

#1980 fix(typeMerging): fix scalar type merging
  packages/stitch/src/mergeCandidates.ts
  packages/stitch/src/stitchSchemas.ts
  packages/stitch/src/stitchingInfo.ts
  packages/stitch/src/typeCandidates.ts
  packages/stitch/src/types.ts
  website/docs/stitch-type-merging.md
Labels: bugfix

#1991 fix(url-loader): should preserve ws and http in the middle of a pointer
  packages/loaders/url/src/index.ts
  packages/loaders/url/tests/url-loader.spec.ts
Labels: bugfix

#2001 enhance(stitch): simplify subschema sets
  packages/delegate/src/Subschema.ts
  packages/delegate/src/index.ts
  packages/delegate/src/types.ts
  packages/delegate/tests/batchExecution.test.ts
  packages/stitch/src/stitchSchemas.ts
  packages/stitch/src/stitchingInfo.ts
  packages/stitch/src/types.ts
Labels: enhancement

#1909 Add an additional ES5-compatible bundle
  .gitignore
  bob.config.js
  package.json
  packages/delegate/package.json
  packages/graphql-tag-pluck/package.json
  packages/graphql-tools/package.json
  packages/import/package.json
  packages/links/package.json
  packages/load-files/package.json
  packages/load/package.json
  packages/loaders/git/package.json
  packages/loaders/github/package.json
  packages/relay-operation-optimizer/package.json
  packages/resolvers-composition/package.json
  packages/utils/package.json
  packages/utils/tests/validate-documents.spec.ts
  packages/wrap/package.json
  tsconfig.build.es5.json
  tsconfig.json
  website/package.json
  yarn.lock
Labels: chore

#2002 enhance(docs) simplify merged interface docs
  website/docs/stitch-type-merging.md
Labels: docs

#2009 Make sure to destructure graphqlHTTP out of express-graphql
  website/docs/server-setup.md
Labels: docs

#2018 Increase maxBuffer to 1MB
  packages/loaders/git/src/load-git.ts
Labels: bugfix

#2023 Handle recursive input types when pruning schemas
  packages/utils/src/prune.ts
  packages/utils/tests/prune.test.ts
Labels: bugfix

#1989 Introduce computed fields
  packages/batch-delegate/src/getLoader.ts
  packages/batch-delegate/src/types.ts
  packages/batch-delegate/tests/typeMerging.example.test.ts
  packages/delegate/src/Subschema.ts
  packages/delegate/src/delegateToSchema.ts
  packages/delegate/src/index.ts
  packages/delegate/src/results/mergeProxiedResults.ts
  packages/delegate/src/types.ts
  packages/stitch/src/index.ts
  packages/stitch/src/isolateComputedFields.ts
  packages/stitch/src/stitchSchemas.ts
  packages/stitch/src/stitchingInfo.ts
  packages/stitch/src/subschemaConfigTransforms/computedDirectiveTransformer.ts
  packages/stitch/src/subschemaConfigTransforms/index.ts
  packages/stitch/src/types.ts
  packages/stitch/tests/isolateComputedFields.ts
  packages/stitch/tests/mergeComputedFields.test.ts
  packages/utils/src/filterSchema.ts
  packages/utils/src/types.ts
  packages/wrap/src/transforms/TransformCompositeFields.ts
  website/docs/stitch-combining-schemas.md
  website/docs/stitch-schema-extensions.md
  website/docs/stitch-type-merging.md
  website/sidebars.json
Labels: feature

#2024 Fix bad stitching docs link in README
  README.md
Labels: docs

#2036 Update `Type definitions (SDL) merging` docs
  website/docs/merge-typedefs.md
Labels: docs

#2045 feat(import): support specifiedBy builtin directive
  packages/import/src/index.ts
Labels: feature

#2043 Fix duplication of scalar directives in merge
  packages/merge/tests/merge-schemas.spec.ts
  packages/utils/src/getResolversFromSchema.ts
Labels: bug

#2042 Support scalar extensions by merging directives
  packages/merge/src/typedefs-mergers/merge-nodes.ts
  packages/merge/src/typedefs-mergers/scalar.ts
  packages/merge/tests/merge-typedefs.spec.ts
Labels: enhancement

#2066 docs: Example of using graphql-transport-ws
  website/docs/remote-schemas.md
  website/docs/server-setup.md
Labels: docs
