Repository ardatan/graphql-tools, pull requests merged in 2020-06, with the labels that each got.

#1551 introduce input object field transformers: Filter/Rename/TransformInputObjectFields
  packages/utils/src/Interfaces.ts
  packages/wrap/src/transforms/FilterInputObjectFields.ts
  packages/wrap/src/transforms/RenameInputObjectFields.ts
  packages/wrap/src/transforms/TransformInputObjectFields.ts
  packages/wrap/src/transforms/index.ts
  packages/wrap/src/types.ts
  packages/wrap/tests/transforms.test.ts
Labels: automerge

#1622 Update graphql tag pluck to include flow plugins whenever the code includes @flow
  CHANGELOG.md
  packages/graphql-tag-pluck/src/config.ts
  packages/graphql-tag-pluck/tests/graphql-tag-pluck.test.ts
Labels: automerge

#1648 fix(proxiedResults): handle top level errors when using type merging
  packages/delegate/src/proxiedResult.ts
  packages/stitch/tests/typeMerging.test.ts
Labels: bugfix

#1681 fix for missing enum in build operation node for field method
  packages/utils/src/build-operation-for-field.ts
Labels: bugfix

#1671 fix(merge): add default value for `mergeDirectives`
  packages/merge/src/typedefs-mergers/directives.ts
  packages/merge/tests/merge-typedefs.spec.ts
Labels: bugfix

#1683 Use non-node friendly aggregate error
  packages/delegate/package.json
  packages/delegate/src/delegateToSchema.ts
  packages/delegate/src/results/handleNull.ts
  packages/utils/package.json
  packages/utils/src/validate-documents.ts
  packages/utils/tests/validate-documents.spec.ts
  packages/wrap/src/introspect.ts
  yarn.lock
Labels: automerge, bugfix

#1666 Remove location data from loaded documents to reduce document size
  packages/import/src/index.ts
  packages/relay-operation-optimizer/src/index.ts
  packages/webpack-loader/package.json
  packages/webpack-loader/src/index.ts
  yarn.lock
Labels: automerge, enhancement
