Repository ardatan/graphql-tools, pull requests merged in 2020-08, with the labels that each got.

#1868 chore(batchDelegate): fix property names
  packages/batch-delegate/src/createBatchDelegateFn.ts
  packages/batch-delegate/src/getLoader.ts
  packages/batch-delegate/src/types.ts
  packages/batch-delegate/tests/basic.example.test.ts
  packages/delegate/src/types.ts
  packages/stitch/src/stitchingInfo.ts
  website/docs/schema-stitching.md
Labels: chore

#1883 feat(mergeMocks): support Promise
  packages/mock/src/mocking.ts
  packages/mock/tests/mocking.spec.ts
Labels: feature

#1837 fix: change use of `instanceof Promise` to use `is-promise` library
  packages/delegate/package.json
  packages/delegate/src/delegateToSchema.ts
  packages/delegate/src/results/mergeFields.ts
  packages/links/package.json
  packages/links/src/GraphQLUpload.ts
  packages/stitch/package.json
  packages/stitch/tests/fixtures/schemas.ts
  packages/wrap/package.json
  packages/wrap/tests/fixtures/schemas.ts
  yarn.lock
Labels: bugfix

#1898 fix(url-loader): pass variables correctly on HTTP GET
  packages/loaders/url/src/index.ts
  packages/loaders/url/tests/url-loader.spec.ts
  packages/testing/utils.ts
Labels: bugfix

#1895 Schema stitching documentation
  website/docs/schema-stitching.md
  website/docs/stitch-api.md
  website/docs/stitch-combining-schemas.md
  website/docs/stitch-merging-types.md
  website/docs/stitch-schema-extensions.md
  website/sidebars.json
Labels: docs

#1910 enhance(website) Type Merging docs
  website/docs/stitch-merging-types.md
  website/docs/stitch-schema-extensions.md
  website/docs/stitch-type-merging.md
  website/sidebars.json
Labels: docs

#1917 fix(typeMerging): fix interface merging
  packages/stitch/src/mergeCandidates.ts
  packages/stitch/tests/mergeInterfaces.test.ts
Labels: bugfix

#1953 fix(build-operation-for-field): respect field depth
  packages/utils/src/build-operation-for-field.ts
Labels: bugfix

#1958 fix(typeMerging): field selection sets
  packages/delegate/src/results/mergeFields.ts
  packages/stitch/tests/fieldSelectionSets.test.ts
Labels: bugfix

#1952 fix(mocking): support subscriptions
  packages/mock/src/mocking.ts
  packages/mock/tests/mocking.spec.ts
Labels: bugfix

#1934 Support InputObjectTypeDefinition & InputObjectTypeExtension for getFieldsWithDirectives
  packages/utils/src/get-fields-with-directives.ts
  packages/utils/tests/get-fields-with-directives.spec.ts
Labels: bugfix

#1972 docs: difference between stitching and merging
  website/docs/merge-schemas.md
Labels: docs
