Repository ardatan/graphql-tools, pull requests merged in 2020-10, with the labels that each got.

#2083 feat(url-loader): handle graphql sdl
  .changeset/thick-pumas-compare.md
  packages/loaders/url/src/index.ts
  packages/loaders/url/tests/url-loader.spec.ts
Labels: feature

#2090 Remove $ from invalidPathRegex
  .changeset/odd-moons-hunt.md
  packages/utils/src/helpers.ts
Labels: bugfix

#2138 Update `links` package to use `@apollo/client/links`
  .changeset/new-pears-compete.md
  .changeset/thin-ways-wave.md
  .github/workflows/canary.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
  .github/workflows/website.yml
  package.json
  packages/links/package.json
  packages/links/src/AwaitVariablesLink.ts
  packages/links/src/createServerHttpLink.ts
  packages/links/src/linkToExecutor.ts
  packages/links/src/linkToSubscriber.ts
  packages/loaders/url/src/index.ts
  packages/utils/src/observableToAsyncIterable.ts
  packages/wrap/src/transforms/HoistField.ts
  yarn.lock
Labels: bugfix, enhancement

#2143 feat(graphql-tag-pluck): Support Vue files with TypeScript
  .changeset/silver-zebras-itch.md
  packages/graphql-tag-pluck/src/config.ts
Labels: feature
