Repository ardatan/graphql-tools, pull requests merged in 2020-07, with the labels that each got.

#1716 Use DocumentNode instead of GraphQLResolveInfo to decide the HTTP method for useGETForQueries
  packages/loaders/url/src/index.ts
Labels: bugfix

#1696 fix(loadSchema): add optional chaining
  packages/load/src/schema.ts
Labels: bugfix

#1752 Update loadFilesSync docs for specifying extensions
  website/docs/merge-resolvers.md
  website/docs/merge-typedefs.md
Labels: docs

#1751 Correct loadFilesSync docs
  website/docs/merge-typedefs.md
Labels: docs

#1763 change args order
  packages/delegate/src/delegationBindings.ts
  packages/delegate/src/transforms/AddSelectionSets.ts
Labels: feature

#1767 refactor to rely on mapSchema
  packages/utils/src/fields.ts
  packages/utils/src/mapSchema.ts
  packages/wrap/src/transforms/TransformCompositeFields.ts
  packages/wrap/src/transforms/TransformInputObjectFields.ts
Labels: chore

#1768 refactor out renameTypes function
  packages/utils/src/index.ts
  packages/utils/src/renameType.ts
  packages/wrap/src/transforms/RenameRootTypes.ts
  packages/wrap/src/transforms/RenameTypes.ts
Labels: chore

#1759 Annotate code base with JSDoc comments
  packages/graphql-tag-pluck/src/index.ts
  packages/load-files/src/index.ts
  packages/load/src/documents.ts
  packages/load/src/filter-document-kind.ts
  packages/load/src/load-typedefs.ts
  packages/load/src/schema.ts
  packages/loaders/apollo-engine/src/index.ts
  packages/loaders/code-file/src/exports.ts
  packages/loaders/code-file/src/helpers.ts
  packages/loaders/code-file/src/index.ts
  packages/loaders/code-file/src/load-from-module.ts
  packages/loaders/git/src/index.ts
  packages/loaders/git/src/load-git.ts
  packages/loaders/git/src/parse.ts
  packages/loaders/github/src/index.ts
  packages/loaders/graphql-file/src/index.ts
  packages/loaders/json-file/src/index.ts
  packages/loaders/module/src/index.ts
  packages/loaders/prisma/src/index.ts
  packages/loaders/url/src/index.ts
  packages/merge/src/merge-resolvers.ts
  packages/merge/src/merge-schemas.ts
  packages/merge/src/typedefs-mergers/merge-typedefs.ts
  packages/mock/src/mocking.ts
  packages/mock/src/types.ts
  packages/schema/src/makeExecutableSchema.ts
  packages/schema/src/types.ts
  packages/utils/src/Interfaces.ts
  packages/utils/src/prune.ts
Labels: docs

#1733 fix imports
  website/docs/remote-schemas.md
Labels: docs

#1726 Update schema-directives.md
  website/docs/schema-directives.md
Labels: docs

#1760 Add automatic generation of API documentation
  .github/workflows/website.yml
  package.json
  scripts/build-api-docs.js
  website/docusaurus.config.js
  website/sidebars.js
  website/sidebars.json
  yarn.lock
Labels: docs

#1778 fix(url-loader): send correct data if useGETForQueries is true
  packages/loaders/url/src/index.ts
Labels: bugfix

#1783 fix public signatures for strict option
  packages/utils/src/Interfaces.ts
  packages/wrap/src/transforms/WrapFields.ts
  packages/wrap/src/transforms/WrapType.ts
Labels: bugfix

#1789 feat(merge): support multidimensional arrays for mergeTypeDefs and mergeResolvers
  packages/merge/src/merge-resolvers.ts
  packages/merge/src/typedefs-mergers/merge-typedefs.ts
Labels: enhancement

#1791 fix(utils): avoid global variable
  packages/utils/src/validate-documents.ts
Labels: bugfix

#1796 Refactor GitLoader
  packages/loaders/git/package.json
  packages/loaders/git/src/index.ts
  packages/loaders/git/src/load-git.ts
  packages/loaders/git/tests/loader.spec.ts
  packages/loaders/git/tests/test-files/bad-extension.garphql
  packages/loaders/git/tests/test-files/introspection.json
  packages/loaders/git/tests/test-files/pluckable.ts
  packages/loaders/git/tests/test-files/type-defs.graphql
  packages/loaders/git/tests/test-files/type-defs.json
Labels: enhancement

#1799 fix(transforms): preserve aliases
  packages/stitch/tests/alternateStitchSchemas.test.ts
  packages/wrap/src/transforms/TransformCompositeFields.ts
Labels: bugfix

#1797 Add missing tests for GraphQLFileLoader, JsonFileLoader and ModuleLoader
  packages/loaders/git/tests/loader.spec.ts
  packages/loaders/graphql-file/src/index.ts
  packages/loaders/graphql-file/tests/loader.spec.ts
  packages/loaders/graphql-file/tests/test-files/import-me.graphql
  packages/loaders/graphql-file/tests/test-files/type-defs-with-import.graphql
  packages/loaders/graphql-file/tests/test-files/type-defs.graphql
  packages/loaders/json-file/src/index.ts
  packages/loaders/json-file/tests/loader.spec.ts
  packages/loaders/json-file/tests/test-files/introspection.json
  packages/loaders/json-file/tests/test-files/malformed.json
  packages/loaders/json-file/tests/test-files/type-defs.json
  packages/loaders/module/src/index.ts
  packages/loaders/module/tests/loader.spec.ts
  packages/loaders/module/tests/test-files/schema.js
  packages/loaders/module/tests/test-files/type-defs-named-export.js
  packages/loaders/module/tests/test-files/type-defs-string.js
  packages/loaders/module/tests/test-files/type-defs.js
Labels: testing

#1808 Fix GraphQLFileLoader #import syntax handling
  packages/loaders/graphql-file/src/index.ts
  packages/loaders/graphql-file/tests/loader.spec.ts
  packages/loaders/graphql-file/tests/test-files/executable.graphql
  packages/loaders/graphql-file/tests/test-files/fragment.graphql
  packages/loaders/graphql-file/tests/test-files/import-me.graphql
  packages/loaders/graphql-file/tests/test-files/type-defs-with-import.graphql
Labels: bugfix

#1831 Pluck from @apollo/client/core and apollo-angular
  packages/graphql-tag-pluck/src/visitor.ts
Labels: enhancement

#1838 Fix issue with graphql-upload-client
  packages/links/src/linkToExecutor.ts
  packages/links/src/linkToSubscriber.ts
  packages/links/tests/upload.test.ts
Labels: bugfix

#1841 Pull code from unmaintained prisma-yml package into prisma-loader package.
  packages/loaders/prisma/package.json
  packages/loaders/prisma/src/index.ts
  packages/loaders/prisma/src/prisma-yml/Cluster.test.ts
  packages/loaders/prisma/src/prisma-yml/Cluster.ts
  packages/loaders/prisma/src/prisma-yml/Environment.test.ts
  packages/loaders/prisma/src/prisma-yml/Environment.ts
  packages/loaders/prisma/src/prisma-yml/Output.ts
  packages/loaders/prisma/src/prisma-yml/PrismaDefinition.test.ts
  packages/loaders/prisma/src/prisma-yml/PrismaDefinition.ts
  packages/loaders/prisma/src/prisma-yml/Variables.ts
  packages/loaders/prisma/src/prisma-yml/__snapshots__/Cluster.test.ts.snap
  packages/loaders/prisma/src/prisma-yml/__snapshots__/Environment.test.ts.snap
  packages/loaders/prisma/src/prisma-yml/__snapshots__/PrismaDefinition.test.ts.snap
  packages/loaders/prisma/src/prisma-yml/constants.ts
  packages/loaders/prisma/src/prisma-yml/errors/ClusterNotFound.ts
  packages/loaders/prisma/src/prisma-yml/errors/ClusterNotSet.ts
  packages/loaders/prisma/src/prisma-yml/errors/StageNotFound.ts
  packages/loaders/prisma/src/prisma-yml/index.ts
  packages/loaders/prisma/src/prisma-yml/prisma-json-schema.ts
  packages/loaders/prisma/src/prisma-yml/test/getTmpDir.ts
  packages/loaders/prisma/src/prisma-yml/types/common.ts
  packages/loaders/prisma/src/prisma-yml/types/rc.ts
  packages/loaders/prisma/src/prisma-yml/utils/__snapshots__/parseEndpoint.test.ts.snap
  packages/loaders/prisma/src/prisma-yml/utils/__snapshots__/yamlComment.test.ts.snap
  packages/loaders/prisma/src/prisma-yml/utils/getProxyAgent.ts
  packages/loaders/prisma/src/prisma-yml/utils/parseEndpoint.test.ts
  packages/loaders/prisma/src/prisma-yml/utils/parseEndpoint.ts
  packages/loaders/prisma/src/prisma-yml/utils/yamlComment.test.ts
  packages/loaders/prisma/src/prisma-yml/utils/yamlComment.ts
  packages/loaders/prisma/src/prisma-yml/yaml.ts
  yarn.lock
Labels: enhancement
